org: stephenhky
app: aws-kwan-financial-portfolio
service: aws-kwan-financial-portfolio

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.8


functions:
  finport:
    handler: finport.get_optimized_portfolio
    events:
      - http: GET /
